import type { Vehicle, VehicleAnalysis, AdminConfig } from "./types";
import bmw from "@/assets/car-bmw.jpg";
import mercedes from "@/assets/car-mercedes.jpg";
import audi from "@/assets/car-audi.jpg";
import vw from "@/assets/car-vw.jpg";
import porsche from "@/assets/car-porsche.jpg";
import audiQ5 from "@/assets/car-audi-q5.jpg";
import bmwX3 from "@/assets/car-bmw-x3.jpg";
import mercedesGlc from "@/assets/car-mercedes-glc.jpg";

export const defaultConfig: AdminConfig = {
  eurChfRate: 0.96,
  chfPerKm: 1.2,
  customsFlat: 200,
  mfkFlat: 800,
  preparationFlat: 600,
  targetMarginChf: 3000,
  co2ThresholdGkm: 130,
  scoreWeights: {
    margin: 35,
    priceVsMarket: 25,
    liquidity: 15,
    importRisk: 10,
    demand: 10,
    learning: 5,
  },
};

export const vehicles: Vehicle[] = [
  {
    id: "v1", title: "BMW M340i xDrive M Sport", make: "BMW", model: "M340i",
    year: 2021, mileage: 48200, priceEur: 42900, previousPriceEur: 44500,
    fuelType: "Petrol", transmission: "Automatic", color: "Mineral Silver",
    locationCity: "München", locationCountry: "DE",
    listingUrl: "https://www.mobile.de/", platformId: "MOB-882341",
    sourcePlatform: "mobile.de", image: bmw,
    sellerType: "dealer", sellerName: "BMW Autohaus München GmbH",
    daysListed: 6, createdAt: new Date(Date.now() - 6 * 864e5).toISOString(),
  },
  {
    id: "v2", title: "Mercedes-Benz C 220 d AMG Line", make: "Mercedes-Benz", model: "C 220 d",
    year: 2020, mileage: 76500, priceEur: 28500,
    fuelType: "Diesel", transmission: "Automatic", color: "Obsidian Black",
    locationCity: "Stuttgart", locationCountry: "DE",
    listingUrl: "https://www.mobile.de/", platformId: "MOB-771122",
    sourcePlatform: "mobile.de", image: mercedes,
    sellerType: "dealer", sellerName: "Mercedes Niederlassung Stuttgart",
    daysListed: 3, createdAt: new Date(Date.now() - 3 * 864e5).toISOString(),
  },
  {
    id: "v3", title: "Audi A4 Avant 40 TDI quattro S line", make: "Audi", model: "A4 Avant",
    year: 2022, mileage: 38900, priceEur: 34200, previousPriceEur: 35900,
    fuelType: "Diesel", transmission: "Automatic", color: "Ibis White",
    locationCity: "Ingolstadt", locationCountry: "DE",
    listingUrl: "https://www.mobile.de/", platformId: "MOB-554912",
    sourcePlatform: "mobile.de", image: audi,
    sellerType: "dealer", sellerName: "Audi Zentrum Ingolstadt",
    daysListed: 9, createdAt: new Date(Date.now() - 9 * 864e5).toISOString(),
  },
  {
    id: "v4", title: "VW Golf GTI Performance", make: "Volkswagen", model: "Golf GTI",
    year: 2019, mileage: 89200, priceEur: 22900,
    fuelType: "Petrol", transmission: "Manual", color: "Atlantic Blue",
    locationCity: "Wolfsburg", locationCountry: "DE",
    listingUrl: "https://www.mobile.de/", platformId: "AS-129834",
    sourcePlatform: "autoscout24.de", image: vw,
    sellerType: "private", sellerName: "Privatverkäufer",
    daysListed: 14, createdAt: new Date(Date.now() - 14 * 864e5).toISOString(),
  },
  {
    id: "v5", title: "Porsche 911 Carrera (992)", make: "Porsche", model: "911 Carrera",
    year: 2020, mileage: 32400, priceEur: 109800,
    fuelType: "Petrol", transmission: "Automatic", color: "Guards Red",
    locationCity: "Frankfurt", locationCountry: "DE",
    listingUrl: "https://www.mobile.de/", platformId: "MOB-998812",
    sourcePlatform: "mobile.de", image: porsche,
    sellerType: "dealer", sellerName: "Porsche Zentrum Frankfurt",
    daysListed: 2, createdAt: new Date(Date.now() - 2 * 864e5).toISOString(),
  },
  {
    id: "v6", title: "Audi Q5 45 TFSI quattro S line", make: "Audi", model: "Q5",
    year: 2021, mileage: 54100, priceEur: 39500, previousPriceEur: 41200,
    fuelType: "Petrol", transmission: "Automatic", color: "Daytona Grey",
    locationCity: "Hamburg", locationCountry: "DE",
    listingUrl: "https://www.mobile.de/", platformId: "MOB-664421",
    sourcePlatform: "mobile.de", image: audiQ5,
    sellerType: "dealer", sellerName: "Audi Hamburg",
    daysListed: 11, createdAt: new Date(Date.now() - 11 * 864e5).toISOString(),
  },
  {
    id: "v7", title: "BMW X3 xDrive30e Hybrid", make: "BMW", model: "X3",
    year: 2022, mileage: 41200, priceEur: 44800,
    fuelType: "Hybrid", transmission: "Automatic", color: "Alpine White",
    locationCity: "Berlin", locationCountry: "DE",
    listingUrl: "https://www.mobile.de/", platformId: "MOB-112299",
    sourcePlatform: "mobile.de", image: bmwX3,
    sellerType: "dealer", sellerName: "BMW Niederlassung Berlin",
    daysListed: 5, createdAt: new Date(Date.now() - 5 * 864e5).toISOString(),
  },
  {
    id: "v8", title: "Mercedes-Benz GLC 300 4MATIC", make: "Mercedes-Benz", model: "GLC 300",
    year: 2021, mileage: 62800, priceEur: 41200,
    fuelType: "Petrol", transmission: "Automatic", color: "Obsidian Black",
    locationCity: "Köln", locationCountry: "DE",
    listingUrl: "https://www.mobile.de/", platformId: "AS-447721",
    sourcePlatform: "autoscout24.de", image: mercedesGlc,
    sellerType: "dealer", sellerName: "Mercedes Köln-Süd",
    daysListed: 7, createdAt: new Date(Date.now() - 7 * 864e5).toISOString(),
  },
];

export const analyses: Record<string, VehicleAnalysis> = {
  v1: {
    vehicleId: "v1", distanceKm: 320, transportCostChf: 384,
    importTaxChf: 1648, swissVatChf: 3508, customsChf: 200,
    mfkCostChf: 800, preparationCostChf: 600, eurChfRate: 0.96,
    totalCostChf: 48324, estimatedSellPriceCh: 53900,
    expectedMarginChf: 5576, marketPriceDeAvg: 44800,
    marketPriceChAvg: 54200, priceVsMarketPercent: -4.2,
    dealScore: 84, riskLevel: "low", co2Warning: false, similarListings: 23,
  },
  v2: {
    vehicleId: "v2", distanceKm: 280, transportCostChf: 336,
    importTaxChf: 1095, swissVatChf: 2330, customsChf: 200,
    mfkCostChf: 800, preparationCostChf: 600, eurChfRate: 0.96,
    totalCostChf: 32721, estimatedSellPriceCh: 35900,
    expectedMarginChf: 3179, marketPriceDeAvg: 29900,
    marketPriceChAvg: 36400, priceVsMarketPercent: -4.7,
    dealScore: 76, riskLevel: "low", co2Warning: false, similarListings: 41,
  },
  v3: {
    vehicleId: "v3", distanceKm: 310, transportCostChf: 372,
    importTaxChf: 1314, swissVatChf: 2796, customsChf: 200,
    mfkCostChf: 800, preparationCostChf: 600, eurChfRate: 0.96,
    totalCostChf: 38914, estimatedSellPriceCh: 42900,
    expectedMarginChf: 3986, marketPriceDeAvg: 36100,
    marketPriceChAvg: 43400, priceVsMarketPercent: -5.3,
    dealScore: 81, riskLevel: "low", co2Warning: false, similarListings: 28,
  },
  v4: {
    vehicleId: "v4", distanceKm: 760, transportCostChf: 912,
    importTaxChf: 880, swissVatChf: 1873, customsChf: 200,
    mfkCostChf: 800, preparationCostChf: 600, eurChfRate: 0.96,
    totalCostChf: 27249, estimatedSellPriceCh: 26500,
    expectedMarginChf: -749, marketPriceDeAvg: 21800,
    marketPriceChAvg: 27200, priceVsMarketPercent: 5.0,
    dealScore: 28, riskLevel: "high", co2Warning: true, similarListings: 87,
  },
  v5: {
    vehicleId: "v5", distanceKm: 410, transportCostChf: 492,
    importTaxChf: 4216, swissVatChf: 8979, customsChf: 200,
    mfkCostChf: 800, preparationCostChf: 600, eurChfRate: 0.96,
    totalCostChf: 120695, estimatedSellPriceCh: 132000,
    expectedMarginChf: 11305, marketPriceDeAvg: 114200,
    marketPriceChAvg: 134900, priceVsMarketPercent: -3.8,
    dealScore: 88, riskLevel: "medium", co2Warning: true, similarListings: 12,
  },
  v6: {
    vehicleId: "v6", distanceKm: 720, transportCostChf: 864,
    importTaxChf: 1517, swissVatChf: 3228, customsChf: 200,
    mfkCostChf: 800, preparationCostChf: 600, eurChfRate: 0.96,
    totalCostChf: 44929, estimatedSellPriceCh: 48900,
    expectedMarginChf: 3971, marketPriceDeAvg: 41800,
    marketPriceChAvg: 49400, priceVsMarketPercent: -5.5,
    dealScore: 79, riskLevel: "low", co2Warning: false, similarListings: 35,
  },
  v7: {
    vehicleId: "v7", distanceKm: 880, transportCostChf: 1056,
    importTaxChf: 1721, swissVatChf: 3663, customsChf: 200,
    mfkCostChf: 800, preparationCostChf: 600, eurChfRate: 0.96,
    totalCostChf: 51048, estimatedSellPriceCh: 54900,
    expectedMarginChf: 3852, marketPriceDeAvg: 46900,
    marketPriceChAvg: 55400, priceVsMarketPercent: -4.5,
    dealScore: 73, riskLevel: "medium", co2Warning: false, similarListings: 19,
  },
  v8: {
    vehicleId: "v8", distanceKm: 590, transportCostChf: 708,
    importTaxChf: 1583, swissVatChf: 3370, customsChf: 200,
    mfkCostChf: 800, preparationCostChf: 600, eurChfRate: 0.96,
    totalCostChf: 47013, estimatedSellPriceCh: 49800,
    expectedMarginChf: 2787, marketPriceDeAvg: 43200,
    marketPriceChAvg: 50200, priceVsMarketPercent: -4.6,
    dealScore: 67, riskLevel: "low", co2Warning: false, similarListings: 26,
  },
};
