/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RechnerRouteImport } from './routes/rechner'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as MeineSucheRouteImport } from './routes/meine-suche'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VehicleIdRouteImport } from './routes/vehicle.$id'
import { Route as ApiPublicHooksTestJinaRouteImport } from './routes/api/public/hooks/test-jina'
import { Route as ApiPublicHooksSyncGmailRouteImport } from './routes/api/public/hooks/sync-gmail'
import { Route as ApiPublicHooksScrapeBatchRouteImport } from './routes/api/public/hooks/scrape-batch'
import { Route as ApiPublicHooksResolveReviewQueueRouteImport } from './routes/api/public/hooks/resolve-review-queue'
import { Route as ApiPublicHooksExtensionUnavailableRouteImport } from './routes/api/public/hooks/extension-unavailable'
import { Route as ApiPublicHooksExtensionQueueRouteImport } from './routes/api/public/hooks/extension-queue'
import { Route as ApiPublicHooksExtensionIngestRouteImport } from './routes/api/public/hooks/extension-ingest'
import { Route as ApiPublicHooksExtensionErrorRouteImport } from './routes/api/public/hooks/extension-error'
import { Route as ApiPublicHooksBackfillMwstRouteImport } from './routes/api/public/hooks/backfill-mwst'

const RechnerRoute = RechnerRouteImport.update({
  id: '/rechner',
  path: '/rechner',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const MeineSucheRoute = MeineSucheRouteImport.update({
  id: '/meine-suche',
  path: '/meine-suche',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VehicleIdRoute = VehicleIdRouteImport.update({
  id: '/vehicle/$id',
  path: '/vehicle/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksTestJinaRoute = ApiPublicHooksTestJinaRouteImport.update({
  id: '/api/public/hooks/test-jina',
  path: '/api/public/hooks/test-jina',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSyncGmailRoute = ApiPublicHooksSyncGmailRouteImport.update({
  id: '/api/public/hooks/sync-gmail',
  path: '/api/public/hooks/sync-gmail',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksScrapeBatchRoute =
  ApiPublicHooksScrapeBatchRouteImport.update({
    id: '/api/public/hooks/scrape-batch',
    path: '/api/public/hooks/scrape-batch',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksResolveReviewQueueRoute =
  ApiPublicHooksResolveReviewQueueRouteImport.update({
    id: '/api/public/hooks/resolve-review-queue',
    path: '/api/public/hooks/resolve-review-queue',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksExtensionUnavailableRoute =
  ApiPublicHooksExtensionUnavailableRouteImport.update({
    id: '/api/public/hooks/extension-unavailable',
    path: '/api/public/hooks/extension-unavailable',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksExtensionQueueRoute =
  ApiPublicHooksExtensionQueueRouteImport.update({
    id: '/api/public/hooks/extension-queue',
    path: '/api/public/hooks/extension-queue',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksExtensionIngestRoute =
  ApiPublicHooksExtensionIngestRouteImport.update({
    id: '/api/public/hooks/extension-ingest',
    path: '/api/public/hooks/extension-ingest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksExtensionErrorRoute =
  ApiPublicHooksExtensionErrorRouteImport.update({
    id: '/api/public/hooks/extension-error',
    path: '/api/public/hooks/extension-error',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksBackfillMwstRoute =
  ApiPublicHooksBackfillMwstRouteImport.update({
    id: '/api/public/hooks/backfill-mwst',
    path: '/api/public/hooks/backfill-mwst',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/archive': typeof ArchiveRoute
  '/meine-suche': typeof MeineSucheRoute
  '/queue': typeof QueueRoute
  '/rechner': typeof RechnerRoute
  '/vehicle/$id': typeof VehicleIdRoute
  '/api/public/hooks/backfill-mwst': typeof ApiPublicHooksBackfillMwstRoute
  '/api/public/hooks/extension-error': typeof ApiPublicHooksExtensionErrorRoute
  '/api/public/hooks/extension-ingest': typeof ApiPublicHooksExtensionIngestRoute
  '/api/public/hooks/extension-queue': typeof ApiPublicHooksExtensionQueueRoute
  '/api/public/hooks/extension-unavailable': typeof ApiPublicHooksExtensionUnavailableRoute
  '/api/public/hooks/resolve-review-queue': typeof ApiPublicHooksResolveReviewQueueRoute
  '/api/public/hooks/scrape-batch': typeof ApiPublicHooksScrapeBatchRoute
  '/api/public/hooks/sync-gmail': typeof ApiPublicHooksSyncGmailRoute
  '/api/public/hooks/test-jina': typeof ApiPublicHooksTestJinaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/archive': typeof ArchiveRoute
  '/meine-suche': typeof MeineSucheRoute
  '/queue': typeof QueueRoute
  '/rechner': typeof RechnerRoute
  '/vehicle/$id': typeof VehicleIdRoute
  '/api/public/hooks/backfill-mwst': typeof ApiPublicHooksBackfillMwstRoute
  '/api/public/hooks/extension-error': typeof ApiPublicHooksExtensionErrorRoute
  '/api/public/hooks/extension-ingest': typeof ApiPublicHooksExtensionIngestRoute
  '/api/public/hooks/extension-queue': typeof ApiPublicHooksExtensionQueueRoute
  '/api/public/hooks/extension-unavailable': typeof ApiPublicHooksExtensionUnavailableRoute
  '/api/public/hooks/resolve-review-queue': typeof ApiPublicHooksResolveReviewQueueRoute
  '/api/public/hooks/scrape-batch': typeof ApiPublicHooksScrapeBatchRoute
  '/api/public/hooks/sync-gmail': typeof ApiPublicHooksSyncGmailRoute
  '/api/public/hooks/test-jina': typeof ApiPublicHooksTestJinaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/archive': typeof ArchiveRoute
  '/meine-suche': typeof MeineSucheRoute
  '/queue': typeof QueueRoute
  '/rechner': typeof RechnerRoute
  '/vehicle/$id': typeof VehicleIdRoute
  '/api/public/hooks/backfill-mwst': typeof ApiPublicHooksBackfillMwstRoute
  '/api/public/hooks/extension-error': typeof ApiPublicHooksExtensionErrorRoute
  '/api/public/hooks/extension-ingest': typeof ApiPublicHooksExtensionIngestRoute
  '/api/public/hooks/extension-queue': typeof ApiPublicHooksExtensionQueueRoute
  '/api/public/hooks/extension-unavailable': typeof ApiPublicHooksExtensionUnavailableRoute
  '/api/public/hooks/resolve-review-queue': typeof ApiPublicHooksResolveReviewQueueRoute
  '/api/public/hooks/scrape-batch': typeof ApiPublicHooksScrapeBatchRoute
  '/api/public/hooks/sync-gmail': typeof ApiPublicHooksSyncGmailRoute
  '/api/public/hooks/test-jina': typeof ApiPublicHooksTestJinaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/archive'
    | '/meine-suche'
    | '/queue'
    | '/rechner'
    | '/vehicle/$id'
    | '/api/public/hooks/backfill-mwst'
    | '/api/public/hooks/extension-error'
    | '/api/public/hooks/extension-ingest'
    | '/api/public/hooks/extension-queue'
    | '/api/public/hooks/extension-unavailable'
    | '/api/public/hooks/resolve-review-queue'
    | '/api/public/hooks/scrape-batch'
    | '/api/public/hooks/sync-gmail'
    | '/api/public/hooks/test-jina'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/archive'
    | '/meine-suche'
    | '/queue'
    | '/rechner'
    | '/vehicle/$id'
    | '/api/public/hooks/backfill-mwst'
    | '/api/public/hooks/extension-error'
    | '/api/public/hooks/extension-ingest'
    | '/api/public/hooks/extension-queue'
    | '/api/public/hooks/extension-unavailable'
    | '/api/public/hooks/resolve-review-queue'
    | '/api/public/hooks/scrape-batch'
    | '/api/public/hooks/sync-gmail'
    | '/api/public/hooks/test-jina'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/archive'
    | '/meine-suche'
    | '/queue'
    | '/rechner'
    | '/vehicle/$id'
    | '/api/public/hooks/backfill-mwst'
    | '/api/public/hooks/extension-error'
    | '/api/public/hooks/extension-ingest'
    | '/api/public/hooks/extension-queue'
    | '/api/public/hooks/extension-unavailable'
    | '/api/public/hooks/resolve-review-queue'
    | '/api/public/hooks/scrape-batch'
    | '/api/public/hooks/sync-gmail'
    | '/api/public/hooks/test-jina'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ArchiveRoute: typeof ArchiveRoute
  MeineSucheRoute: typeof MeineSucheRoute
  QueueRoute: typeof QueueRoute
  RechnerRoute: typeof RechnerRoute
  VehicleIdRoute: typeof VehicleIdRoute
  ApiPublicHooksBackfillMwstRoute: typeof ApiPublicHooksBackfillMwstRoute
  ApiPublicHooksExtensionErrorRoute: typeof ApiPublicHooksExtensionErrorRoute
  ApiPublicHooksExtensionIngestRoute: typeof ApiPublicHooksExtensionIngestRoute
  ApiPublicHooksExtensionQueueRoute: typeof ApiPublicHooksExtensionQueueRoute
  ApiPublicHooksExtensionUnavailableRoute: typeof ApiPublicHooksExtensionUnavailableRoute
  ApiPublicHooksResolveReviewQueueRoute: typeof ApiPublicHooksResolveReviewQueueRoute
  ApiPublicHooksScrapeBatchRoute: typeof ApiPublicHooksScrapeBatchRoute
  ApiPublicHooksSyncGmailRoute: typeof ApiPublicHooksSyncGmailRoute
  ApiPublicHooksTestJinaRoute: typeof ApiPublicHooksTestJinaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rechner': {
      id: '/rechner'
      path: '/rechner'
      fullPath: '/rechner'
      preLoaderRoute: typeof RechnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meine-suche': {
      id: '/meine-suche'
      path: '/meine-suche'
      fullPath: '/meine-suche'
      preLoaderRoute: typeof MeineSucheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicle/$id': {
      id: '/vehicle/$id'
      path: '/vehicle/$id'
      fullPath: '/vehicle/$id'
      preLoaderRoute: typeof VehicleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/test-jina': {
      id: '/api/public/hooks/test-jina'
      path: '/api/public/hooks/test-jina'
      fullPath: '/api/public/hooks/test-jina'
      preLoaderRoute: typeof ApiPublicHooksTestJinaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-gmail': {
      id: '/api/public/hooks/sync-gmail'
      path: '/api/public/hooks/sync-gmail'
      fullPath: '/api/public/hooks/sync-gmail'
      preLoaderRoute: typeof ApiPublicHooksSyncGmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/scrape-batch': {
      id: '/api/public/hooks/scrape-batch'
      path: '/api/public/hooks/scrape-batch'
      fullPath: '/api/public/hooks/scrape-batch'
      preLoaderRoute: typeof ApiPublicHooksScrapeBatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/resolve-review-queue': {
      id: '/api/public/hooks/resolve-review-queue'
      path: '/api/public/hooks/resolve-review-queue'
      fullPath: '/api/public/hooks/resolve-review-queue'
      preLoaderRoute: typeof ApiPublicHooksResolveReviewQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/extension-unavailable': {
      id: '/api/public/hooks/extension-unavailable'
      path: '/api/public/hooks/extension-unavailable'
      fullPath: '/api/public/hooks/extension-unavailable'
      preLoaderRoute: typeof ApiPublicHooksExtensionUnavailableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/extension-queue': {
      id: '/api/public/hooks/extension-queue'
      path: '/api/public/hooks/extension-queue'
      fullPath: '/api/public/hooks/extension-queue'
      preLoaderRoute: typeof ApiPublicHooksExtensionQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/extension-ingest': {
      id: '/api/public/hooks/extension-ingest'
      path: '/api/public/hooks/extension-ingest'
      fullPath: '/api/public/hooks/extension-ingest'
      preLoaderRoute: typeof ApiPublicHooksExtensionIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/extension-error': {
      id: '/api/public/hooks/extension-error'
      path: '/api/public/hooks/extension-error'
      fullPath: '/api/public/hooks/extension-error'
      preLoaderRoute: typeof ApiPublicHooksExtensionErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/backfill-mwst': {
      id: '/api/public/hooks/backfill-mwst'
      path: '/api/public/hooks/backfill-mwst'
      fullPath: '/api/public/hooks/backfill-mwst'
      preLoaderRoute: typeof ApiPublicHooksBackfillMwstRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ArchiveRoute: ArchiveRoute,
  MeineSucheRoute: MeineSucheRoute,
  QueueRoute: QueueRoute,
  RechnerRoute: RechnerRoute,
  VehicleIdRoute: VehicleIdRoute,
  ApiPublicHooksBackfillMwstRoute: ApiPublicHooksBackfillMwstRoute,
  ApiPublicHooksExtensionErrorRoute: ApiPublicHooksExtensionErrorRoute,
  ApiPublicHooksExtensionIngestRoute: ApiPublicHooksExtensionIngestRoute,
  ApiPublicHooksExtensionQueueRoute: ApiPublicHooksExtensionQueueRoute,
  ApiPublicHooksExtensionUnavailableRoute:
    ApiPublicHooksExtensionUnavailableRoute,
  ApiPublicHooksResolveReviewQueueRoute: ApiPublicHooksResolveReviewQueueRoute,
  ApiPublicHooksScrapeBatchRoute: ApiPublicHooksScrapeBatchRoute,
  ApiPublicHooksSyncGmailRoute: ApiPublicHooksSyncGmailRoute,
  ApiPublicHooksTestJinaRoute: ApiPublicHooksTestJinaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
