/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RechnerRouteImport } from './routes/rechner'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as MeineSucheRouteImport } from './routes/meine-suche'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VehicleIdRouteImport } from './routes/vehicle.$id'
import { Route as ApiPublicHooksSyncGmailRouteImport } from './routes/api/public/hooks/sync-gmail'

const RechnerRoute = RechnerRouteImport.update({
  id: '/rechner',
  path: '/rechner',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const MeineSucheRoute = MeineSucheRouteImport.update({
  id: '/meine-suche',
  path: '/meine-suche',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VehicleIdRoute = VehicleIdRouteImport.update({
  id: '/vehicle/$id',
  path: '/vehicle/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSyncGmailRoute = ApiPublicHooksSyncGmailRouteImport.update({
  id: '/api/public/hooks/sync-gmail',
  path: '/api/public/hooks/sync-gmail',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/archive': typeof ArchiveRoute
  '/meine-suche': typeof MeineSucheRoute
  '/queue': typeof QueueRoute
  '/rechner': typeof RechnerRoute
  '/vehicle/$id': typeof VehicleIdRoute
  '/api/public/hooks/sync-gmail': typeof ApiPublicHooksSyncGmailRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/archive': typeof ArchiveRoute
  '/meine-suche': typeof MeineSucheRoute
  '/queue': typeof QueueRoute
  '/rechner': typeof RechnerRoute
  '/vehicle/$id': typeof VehicleIdRoute
  '/api/public/hooks/sync-gmail': typeof ApiPublicHooksSyncGmailRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/archive': typeof ArchiveRoute
  '/meine-suche': typeof MeineSucheRoute
  '/queue': typeof QueueRoute
  '/rechner': typeof RechnerRoute
  '/vehicle/$id': typeof VehicleIdRoute
  '/api/public/hooks/sync-gmail': typeof ApiPublicHooksSyncGmailRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/archive'
    | '/meine-suche'
    | '/queue'
    | '/rechner'
    | '/vehicle/$id'
    | '/api/public/hooks/sync-gmail'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/archive'
    | '/meine-suche'
    | '/queue'
    | '/rechner'
    | '/vehicle/$id'
    | '/api/public/hooks/sync-gmail'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/archive'
    | '/meine-suche'
    | '/queue'
    | '/rechner'
    | '/vehicle/$id'
    | '/api/public/hooks/sync-gmail'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ArchiveRoute: typeof ArchiveRoute
  MeineSucheRoute: typeof MeineSucheRoute
  QueueRoute: typeof QueueRoute
  RechnerRoute: typeof RechnerRoute
  VehicleIdRoute: typeof VehicleIdRoute
  ApiPublicHooksSyncGmailRoute: typeof ApiPublicHooksSyncGmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rechner': {
      id: '/rechner'
      path: '/rechner'
      fullPath: '/rechner'
      preLoaderRoute: typeof RechnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meine-suche': {
      id: '/meine-suche'
      path: '/meine-suche'
      fullPath: '/meine-suche'
      preLoaderRoute: typeof MeineSucheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicle/$id': {
      id: '/vehicle/$id'
      path: '/vehicle/$id'
      fullPath: '/vehicle/$id'
      preLoaderRoute: typeof VehicleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-gmail': {
      id: '/api/public/hooks/sync-gmail'
      path: '/api/public/hooks/sync-gmail'
      fullPath: '/api/public/hooks/sync-gmail'
      preLoaderRoute: typeof ApiPublicHooksSyncGmailRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ArchiveRoute: ArchiveRoute,
  MeineSucheRoute: MeineSucheRoute,
  QueueRoute: QueueRoute,
  RechnerRoute: RechnerRoute,
  VehicleIdRoute: VehicleIdRoute,
  ApiPublicHooksSyncGmailRoute: ApiPublicHooksSyncGmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
